version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: yes
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root
      
  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
      
  ApplicationStop:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: root
