version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Version LTS actuelle
    commands:
      - echo "Installing dependencies"
      - apt-get update
      
  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Checking for security vulnerabilities"
      
  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "No compilation needed for static HTML"
      
  post_build:
    commands:
      - echo "Post-build phase completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: .
